# Martin Holdrege

# Script Started 12/9/20

# First stab at manipulating precipitation intensity from the wx database.

# dependencies ------------------------------------------------------------

library(tidyverse)
library(DBI)
library(precipr) # devtools::install_github("MartinHoldrege/precipr")
source("scripts/functions.R")
theme_set(theme_classic())

# connect to database -----------------------------------------------------

db_path <- "../dbWeather/dbWeatherData_STEPWAT2_200sites.sqlite3"

db <- dbConnect(RSQLite::SQLite(), db_path)

rSOILWAT2::dbW_setConnection(db_path, check_version = TRUE)


# load markov ppt ---------------------------------------------------------
# see readme in ppt folder
# ppt generated by stepwat2 markov process

ppt_path <- "../sitedata/ppt"

ppt_2x <- read_csv(file.path(ppt_path, "markov_ppt_2x-intensity_20210104.csv"))

ppt_ambient <- read_csv(file.path(
  ppt_path,  "markov_ppt_ambient-intensity_20210103.csv"))

ppt_markov <- bind_rows(ppt_ambient, ppt_2x) %>% 
  rename(PPT = PRECIP_ppt_Mean, site = siteid, year = Year, DOY = Day,
         manip = intensity) %>% 
  select(-gcm) %>%  # don't need col b/ all current intensity
  mutate(markov = TRUE) # sim by markov process.

# examine db --------------------------------------------------------------

dbListTables(db)
dbGetQuery(db, 'SELECT * FROM Scenarios')
dbGetQuery(db, 'SELECT * FROM wd_all LIMIT 10')


# extract current scenarios -----------------------------------------------

# Diverse set of representative sites from KP
sites <- c(5, 15, 74, 76, 102, 103, 119, 124, 141, 156, 162, 172, 177, 184)

climate.conditions <- "Current"

# code below is from WeatherQuery.R

#Weather query script to extract respective weather data for all scenarios from a pre-generated weather database into a list (sw_weatherList)


#Connecting to the database


#Functions to access respective data

#Function to extract data for a specific site
.local <- function(sid){
  i_sw_weatherList <- list()
  for(k in seq_along(climate.conditions))
    i_sw_weatherList[[k]] <- rSOILWAT2::dbW_getWeatherData(Site_id=sid, Scenario=climate.conditions[k])
  return(i_sw_weatherList)
  
}

#Function to extract respective data for all sites and save it as a list
extract_data<-function(site_to_extract=NULL)
{
  sw_weatherList <- NULL
  for(i in seq_along(site_to_extract)){
    sw_weatherList[[i]] <- try(.local(sid=site_to_extract[i]), silent=TRUE)
  }
  return (sw_weatherList)
}

sw_weatherList<-extract_data(site_to_extract = sites)
rSOILWAT2::dbW_disconnectConnection()


# extract all precip yrs/sites --------------------------------------------

names(sw_weatherList) <- as.character(sites)

# combine 
comb_wx <- map(sw_weatherList, function(x) {
  # just one scenerio so just one list element for each site?
  combine_yrs(x[[1]])
}) %>% 
  bind_rows(.id = "site") %>% 
  mutate(site = as.numeric(site))


# manipulate precip -------------------------------------------------------

comb_wx2 <- comb_wx %>% 
  arrange(site, year, DOY) %>% 
  # for now grouping by year to insure annual precip unchanged
  group_by(site, year) %>% 
  mutate(dly_2x_intensity = incr_dly_intensity(PPT_cm), # double daily intensity
         event_2x_intensity = incr_event_intensity(PPT_cm)) # double event

manip_lookup <- c("PPT_cm" = "ambient", "dly_2x_intensity" = "dly 2x intensity",
                  "event_2x_intensity" = "event 2x intensity")

comb_wx_long <- comb_wx2 %>% 
  pivot_longer(matches("PPT_cm|_intensity"), names_to = "manip", 
               values_to = "PPT") %>% 
  mutate(manip = manip_lookup[manip])

# yearly summaries
yrly_df_all <- comb_wx_long %>% 
  select(-Tmax_C, -Tmin_C) %>% 
  mutate(markov = FALSE) %>% 
  bind_rows(ppt_markov) %>% 
  # yearly summaries
  group_by(site, year, manip, markov) %>% 
  summarise(# number of days with precip
            n_days = sum(PPT > 0),
            # annual precip
            ap = sum(PPT),
            # mean precip on days w/ precip
            mean_PPT = ap/n_days,
            med_PPT = median(PPT[PPT > 0]),
            n_events = n_events(PPT, min_length = 1),
            n_multi_events = n_events(PPT, min_length = 2),
            max_event_length = max_event_length(PPT),
            prop_multi_events = n_multi_events/n_events,
            mean_event_size = mean_event_size(PPT),
            n_small = sum(PPT > 0 & PPT < 0.1)) # number of small events

# only original (db) wx
yrly_df <- yrly_df_all %>% 
  filter(!markov)

# compare original and markov ---------------------------------------------

comb_wx_long2 <- comb_wx_long %>% 
  filter(manip %in% c("ambient", "event 2x intensity")) %>% 
  select(-Tmax_C, -Tmin_C) %>% 
  mutate(markov = FALSE) %>%  # not simulated by stepwat--ie from wx db
  bind_rows(ppt_markov)

yrly_df_all2 <- yrly_df_all %>% 
  filter(manip %in% c("ambient", "event 2x intensity"))

# monthly precip ----------------------------------------------------------

# monthly mean ppt across years within a site. 
monthly_ppt <- comb_wx_long2 %>% 
  mutate(date = as.Date(DOY-1, origin = paste0(year, "-01-01")),
         month = lubridate::month(date)) %>% 
  group_by(year, month, site, manip, markov) %>% 
  summarize(PPT = sum(PPT)) %>% 
  group_by(month, site, manip, markov) %>% 
  summarize(PPT_sd = sd(PPT),
            PPT_m = mean(PPT),
            PPT_med = median(PPT))
  
        
  
# figure functions --------------------------------------------------------

if (!dir.exists("figures")) {
  dir.create("figures")
}

wrap_site <- function(x) {
  fig1 <-  x + facet_wrap(~site) + 
    labs(subtitle = "by site")
  fig2 <- x + facet_wrap(~site, scales = "free") + 
    labs(subtitle = "by site, scales differ")
  
  list(fig1, fig2)
}

density_rug <- function(x) {
  list(geom_density(aes(.data[[x]])),
       geom_rug(aes(.data[[x]]), sides = "b"))
}

cols1 <- c("blue", "black", "red") 
cols2 <- c("blue", "red")
# distributional figures --------------------------------------------------


pdf("figures/ambient_vs_intensity_distributions_v1.pdf")

g <- ggplot(comb_wx_long[comb_wx_long$PPT > 0, ], 
            aes(x = PPT, color = manip)) +
  geom_density() +
  labs(x = "Daily PPT (cm)",
       title = "Intensity increased by adding odd ppt days/events to evens") +
  scale_color_manual(values =cols1)

wrap_site(g)


# distributions of yrly stats ---------------------------------------------

g2 <- ggplot(yrly_df, aes(color = manip)) +
  scale_color_manual(values = cols1) +
  labs(subtitle = "by site",
       caption = "Distributions of yearly summaries")


g4 <- g2 +
  density_rug("med_PPT") +
  labs(title = "Median daily PPT on days with PPT")

wrap_site(g4)

g5 <- g2 +
  density_rug("mean_PPT") +
  labs(title = "Mean daily PPT on days with PPT")

wrap_site(g5)

g6 <- g2 +
  density_rug("ap") +
  labs(title = "Annual precip",
       x = "Annual PPT (cm)")

wrap_site(g6)

g3 <- g2 +
  density_rug("n_days") +
  labs(title = "number of days per year with precip")

wrap_site(g3) 

g7 <- g2 +
  density_rug("n_events") +
  labs(title = "Number of precipitation events (periods with 1 or more consecutive rain days)",
       x = "N events")

wrap_site(g7) 

g8 <- g2 +
  density_rug("n_multi_events") +
  labs(title = "Number of multiday (>=2 days) precip events",
       x = "N events)")
wrap_site(g8)
g9 <- g2 +
  density_rug("max_event_length") +
  labs(title = "Maximum event length (number of consecutive days)",
       x = "Days")
wrap_site(g9)

g10 <- g2 +
  density_rug("prop_multi_events") +
  labs(title = "Proportion of precip events that are multiday",
       x = "Proportion")
wrap_site(g10)

g11 <- g2 +
  density_rug("mean_event_size") +
  labs(title = "Mean event size (event = consecutive ppt days)",
       x = "Mean event size (cm)")
wrap_site(g11)

dev.off()


# figs--markov vs original ------------------------------------------------


pdf("figures/original_vs_markov_distributions_v1.pdf")

# * figs -- daily distributions -------------------------------------------

ggplot(comb_wx_long2[comb_wx_long2$PPT > 0, ], 
            aes(x = PPT, color = manip, linetype = markov)) +
  geom_density() +
  labs(x = "Daily PPT (cm)",
       title = "Daily event size (days > 0 ppt), original vs markov simulated") +
  scale_color_manual(values =cols2) +
  facet_wrap(~site, scales = "free")

# * figs -- yrly distributions -------------------------------------------

# distributions of yrly stats ---------------------------------------------

g2 <- ggplot(yrly_df_all2, aes(color = manip, linetype = markov)) +
  scale_color_manual(values = cols2) +
  labs(subtitle = "by site",
       caption = "Distributions of yearly summaries, markov vs original")


g <- g2 +
  geom_density(aes(med_PPT)) +
  labs(title = "Median daily PPT on days with PPT")

wrap_site(g)

g <- g2 +
  geom_density(aes(mean_PPT)) +
  labs(title = "Mean daily PPT on days with PPT")

wrap_site(g)

g <- g2 +
  geom_density(aes(ap)) +
  labs(title = "Annual precip",
       x = "Annual PPT (cm)")

wrap_site(g)

g <- g2 +
  geom_density(aes(n_days)) +
  labs(title = "number of days per year with precip")

wrap_site(g) 

g <- g2 +
  geom_density(aes(n_events)) +
  labs(title = "Number of precipitation events (periods with 1 or more consecutive rain days)",
       x = "N events")

wrap_site(g) 

g <- g2 +
  geom_density(aes(n_multi_events)) +
  labs(title = "Number of multiday (>=2 days) precip events",
       x = "N events)")
wrap_site(g)
g<- g2 +
  geom_density(aes(max_event_length)) +
  labs(title = "Maximum event length (number of consecutive days)",
       x = "Days")
wrap_site(g)

g <- g2 +
  geom_density(aes(prop_multi_events))+
  labs(title = "Proportion of precip events that are multiday",
       x = "Proportion")
wrap_site(g)

g <- g2 +
  geom_density(aes(mean_event_size)) +
  labs(title = "Mean event size (event = consecutive ppt days)",
       x = "Mean event size (cm)")
wrap_site(g)

dev.off()

# * figs--monthly mean ppt ------------------------------------------------
pdf("figures/original_vs_markov_monthly_PPT_v1.pdf")

p <- ggplot(monthly_ppt, aes(x = month, color = manip, linetype = markov)) +
  facet_wrap(~site) +
  scale_color_manual(values = cols2) +
  scale_x_continuous(breaks = 1:12) 

p +
  geom_line(aes(y = PPT_m)) +
  labs(y = "PPT (cm)",
       subtitle = "Mean monthly precipitation")

p +
  geom_line(aes(y = PPT_med)) +
  labs(y = "PPT (cm)",
       subtitle = "Median monthly precipitation")
dev.off()