# Martin Holdrege

# Script Started 12/9/20

# First stab at manipulating precipitation intensity from the wx database.

# dependencies ------------------------------------------------------------

library(tidyverse)
library(lubridate)
library(DBI)
library(precipr) # devtools::install_github("MartinHoldrege/precipr")
library(rSOILWAT2)

source("scripts/functions.R")
theme_set(theme_classic())

# connect to database -----------------------------------------------------

db_path <- "../dbWeather/dbWeatherData_STEPWAT2_200sites.sqlite3"

rSOILWAT2::dbW_setConnection(db_path, check_version = TRUE)

# load markov ppt ---------------------------------------------------------

# ppt generated by stepwat2 and adjusted coeff files in the 01_
# simulate-wx_14site.R script

ppt_path <- "../sitedata/ppt/markov_ppt_14sites_20210407.csv"
ppt_markov0<- read_csv(ppt_path)

ppt_markov <- ppt_markov0 %>% 
  rename(PPT = PPT_cm, year = Year, manip = intensity) %>% 
  mutate(markov = TRUE) # sim by markov process.

# extract current scenarios -----------------------------------------------

# Diverse set of representative sites from KP
sites <- c(5, 15, 74, 76, 102, 103, 119, 124, 141, 156, 162, 172, 177, 184)
names(sites) <- as.character(sites)
sw_weatherList<- map(sites, dbW_getWeatherData, Scenario = "Current")

# extract all precip yrs/sites --------------------------------------------

# combine into single df
comb_wx <- map_dfr(sw_weatherList, function(x) {
  wdata_df <- dbW_weatherData_to_dataframe(x) %>% 
    as.data.frame()
}, .id = "site") %>% 
  mutate(site = as.numeric(site)) %>% 
  rename(year = Year)

# saving file of just site 5 for code testing
comb_wx %>% 
  filter(site == 5) %>% 
  mutate(first = paste0(year, "-01-01"),
         date = as.Date((DOY-1), origin = first),
         month = month(date),
         day = mday(date)) %>% 
  select(site, year, month, day, date, everything(), -first) %>% 
  write_csv("data-raw/wx_ambient_site-5.csv")

# manipulate precip -------------------------------------------------------

comb_wx2 <- comb_wx %>% 
  arrange(site, year, DOY) %>% 
  # for now grouping by year to insure annual precip unchanged
  group_by(site, year) %>% 
  mutate(dly_2x_intensity = incr_dly_intensity(PPT_cm), # double daily intensity
         event_2x_intensity = incr_event_intensity(PPT_cm)) # double event

manip_lookup <- c("PPT_cm" = "ambient", "dly_2x_intensity" = "dly 2x intensity",
                  "event_2x_intensity" = "event 2x intensity")

comb_wx_long <- comb_wx2 %>% 
  pivot_longer(matches("PPT_cm|_intensity"), names_to = "manip", 
               values_to = "PPT") %>% 
  mutate(manip = manip_lookup[manip])

# yearly summaries

yrly_df_all <- comb_wx_long %>% 
  mutate(markov = FALSE) %>% 
  bind_rows(ppt_markov) %>% 
  # yearly summaries
  group_by(site, year, manip, markov) %>% 
  summarise(# number of days with precip
            n_days = sum(PPT > 0),
            # annual precip
            ap = sum(PPT),
            # mean precip on days w/ precip
            mean_PPT = ap/n_days,
            med_PPT = median(PPT[PPT > 0]),
            n_events = n_events(PPT, min_length = 1),
            n_multi_events = n_events(PPT, min_length = 2),
            max_event_length = max_event_length(PPT),
            prop_multi_events = n_multi_events/n_events,
            mean_event_size = mean_event_size(PPT),
            n_small = sum(PPT > 0 & PPT < 0.1),
            mean_Tmax = mean(Tmax_C),
            mean_Tmin = mean(Tmin_C)) # number of small events

# note this year has 0 ppt. Is that just chance or an issue with 
# the coeff adjustment?
yrly_df_all %>% 
  filter(ap == 0)

# only original (db) wx
yrly_df <- yrly_df_all %>% 
  filter(!markov)

# compare original and markov ---------------------------------------------

comb_wx_long2 <- comb_wx_long %>% 
  # now just looking at original ambient
  # filter(manip %in% c("ambient", "event 2x intensity"))
  filter(manip %in% c("ambient")) %>% 
  mutate(markov = FALSE) %>%  # not simulated by stepwat--ie from wx db
  bind_rows(ppt_markov)

yrly_df_all2 <- yrly_df_all %>% 
  filter(manip %in% c("ambient", "event 2x intensity"))


# compare distributions by DOY --------------------------------------------
# trying to see what family of distribution is being used by the weather generator
# note, days without rain on the previous day are treated differently 
# so seperating them

# daily ambient data
dly_amb <- comb_wx_long2 %>% 
  # to reduce size of df
  filter(manip == "ambient") %>% 
  mutate(DOY = as.factor(DOY))

# daily ppt greater than 0
dly_amb_gt0 <- dly_amb %>% 
  arrange(manip, markov, site, year, DOY) %>% 
  group_by(manip, markov, site) %>% 
  mutate(# was there ppt on previous
         is_prev_wet = is_prev_wet(PPT)) %>% 
  # first day in time series will have NA
  filter(!is.na(.data$is_prev_wet), PPT > 0) %>% 
  ungroup()


# monthly precip ----------------------------------------------------------

# monthly mean ppt across years within a site. 
monthly_ppt <- comb_wx_long2 %>% 
  mutate(date = as.Date(DOY-1, origin = paste0(year, "-01-01")),
         month = lubridate::month(date)) %>% 
  group_by(year, month, site, manip, markov) %>% 
  summarize(PPT = sum(PPT),
            Tmax_C = mean(Tmax_C),
            Tmin_C = mean(Tmin_C), 
            .groups = "drop") %>% 
  group_by(month, site, manip, markov) %>% 
  summarize(PPT_sd = sd(PPT),
            PPT_m = mean(PPT),
            PPT_med = median(PPT),
            Tmax_sd = sd(Tmax_C),
            Tmax_m = mean(Tmax_C),
            Tmax_med = median(Tmax_C),
            Tmin_sd = sd(Tmin_C),
            Tmin_m = mean(Tmin_C),
            Tmin_med = median(Tmin_C),
            .groups = "drop")
  

# mean_annual_diffs -------------------------------------------------------
# mean diffs of temp and precip
        
diffs_mean_annual <- yrly_df_all %>% 
  filter(!str_detect(manip, "dly|event")) %>% 
  group_by(site, manip, markov) %>% 
  summarize(map = mean(ap),
            Tmax = mean(mean_Tmax),
            Tmin = mean(mean_Tmin),
            .groups = "drop") %>% 
  mutate(manip = str_replace(manip, " ", "_"),
         manip_markov = paste(manip, markov, sep = "_")) %>% 
  select(-manip, -markov) %>% 
  pivot_wider(id_cols = c("site"),
              values_from = c("map", "Tmax", "Tmin"),
              names_from = "manip_markov") %>% 
  mutate(site = as.character(site),
         site = factor(site, levels = sites),
         # difference between original and simulated ambient map
         map_orig_amb_diff =  map_ambient_TRUE - map_ambient_FALSE,
         # original vs simulated 2x map
         map_orig_2x_diff = map_2x_intensity_TRUE - map_ambient_FALSE,
         # simulated ambient vs 2x map
         map_amb_2x_diff = map_2x_intensity_TRUE - map_ambient_TRUE,
         Tmax_orig_amb_diff =  Tmax_ambient_TRUE - Tmax_ambient_FALSE,
         Tmax_orig_2x_diff = Tmax_2x_intensity_TRUE - Tmax_ambient_FALSE,
         Tmax_amb_2x_diff = Tmax_2x_intensity_TRUE - Tmax_ambient_TRUE,
         Tmin_orig_amb_diff =  Tmin_ambient_TRUE - Tmin_ambient_FALSE,
         Tmin_orig_2x_diff = Tmin_2x_intensity_TRUE - Tmin_ambient_FALSE,
         Tmin_amb_2x_diff = Tmin_2x_intensity_TRUE - Tmin_ambient_TRUE
         ) 

# figure functions --------------------------------------------------------

if (!dir.exists("figures")) {
  dir.create("figures")
}

density_rug <- function(x) {
  list(geom_density(aes(.data[[x]])),
       geom_rug(aes(.data[[x]]), sides = "b"))
}

cols1 <- c("blue", "black", "red") 
cols2 <- c("blue", "red")
names(cols2) <- c("ambient", "2x intensity")
# distributional figures --------------------------------------------------

# these figures are no longer really of much interest b/
# I probably won't manipulate intensity this way (e.g. removing from odd and
# add to even events)

if (FALSE){
pdf("figures/ambient_vs_intensity_distributions_v2.pdf")

g <- ggplot(comb_wx_long[comb_wx_long$PPT > 0, ], 
            aes(x = PPT, color = manip)) +
  geom_density() +
  labs(x = "Daily PPT (cm)",
       title = "Intensity increased by adding odd ppt days/events to evens") +
  scale_color_manual(values =cols1)

wrap_site(g)


# distributions of yrly stats ---------------------------------------------

g2 <- ggplot(yrly_df, aes(color = manip)) +
  scale_color_manual(values = cols1) +
  labs(subtitle = "by site",
       caption = "Distributions of yearly summaries")


g4 <- g2 +
  density_rug("med_PPT") +
  labs(title = "Median daily PPT on days with PPT")

wrap_site(g4)

g5 <- g2 +
  density_rug("mean_PPT") +
  labs(title = "Mean daily PPT on days with PPT")

wrap_site(g5)

g6 <- g2 +
  density_rug("ap") +
  labs(title = "Annual precip",
       x = "Annual PPT (cm)")

wrap_site(g6)

g3 <- g2 +
  density_rug("n_days") +
  labs(title = "number of days per year with precip")

wrap_site(g3) 

g7 <- g2 +
  density_rug("n_events") +
  labs(title = "Number of precipitation events (periods with 1 or more consecutive rain days)",
       x = "N events")

wrap_site(g7) 

g8 <- g2 +
  density_rug("n_multi_events") +
  labs(title = "Number of multiday (>=2 days) precip events",
       x = "N events)")
wrap_site(g8)
g9 <- g2 +
  density_rug("max_event_length") +
  labs(title = "Maximum event length (number of consecutive days)",
       x = "Days")
wrap_site(g9)

g10 <- g2 +
  density_rug("prop_multi_events") +
  labs(title = "Proportion of precip events that are multiday",
       x = "Proportion")
wrap_site(g10)

g11 <- g2 +
  density_rug("mean_event_size") +
  labs(title = "Mean event size (event = consecutive ppt days)",
       x = "Mean event size (cm)")
wrap_site(g11)

dev.off()
}

# figs--markov vs original ------------------------------------------------


pdf("figures/original_vs_markov_distributions_v2.pdf")

# * figs -- daily distributions -------------------------------------------

ggplot(comb_wx_long2[comb_wx_long2$PPT > 0, ], 
            aes(x = PPT, color = manip, linetype = markov)) +
  geom_density() +
  labs(x = "Daily PPT (cm)",
       title = "Daily event size (days > 0 ppt), original vs markov simulated") +
  scale_color_manual(values =cols2) +
  facet_wrap(~site, scales = "free")

# * figs -- yrly distributions -------------------------------------------

g2 <- ggplot(yrly_df_all2, aes(color = manip, linetype = markov)) +
  scale_color_manual(values = cols2) +
  labs(subtitle = "by site",
       caption = "Distributions of yearly summaries, markov vs original")


g <- g2 +
  geom_density(aes(med_PPT)) +
  labs(title = "Median daily PPT on days with PPT")

wrap_site(g)

g <- g2 +
  geom_density(aes(mean_PPT)) +
  labs(title = "Mean daily PPT on days with PPT")

wrap_site(g)

g <- g2 +
  geom_density(aes(ap)) +
  labs(title = "Annual precip",
       x = "Annual PPT (cm)")

wrap_site(g)

g <- g2 +
  geom_density(aes(n_days)) +
  labs(title = "number of days per year with precip")

wrap_site(g) 

g <- g2 +
  geom_density(aes(n_events)) +
  labs(title = "Number of precipitation events (periods with 1 or more consecutive rain days)",
       x = "N events")

wrap_site(g) 

g <- g2 +
  geom_density(aes(n_multi_events)) +
  labs(title = "Number of multiday (>=2 days) precip events",
       x = "N events)")
wrap_site(g)
g<- g2 +
  geom_density(aes(max_event_length)) +
  labs(title = "Maximum event length (number of consecutive days)",
       x = "Days")
wrap_site(g)

g <- g2 +
  geom_density(aes(prop_multi_events))+
  labs(title = "Proportion of precip events that are multiday",
       x = "Proportion")
wrap_site(g)

g <- g2 +
  geom_density(aes(mean_event_size)) +
  labs(title = "Mean event size (event = consecutive ppt days)",
       x = "Mean event size (cm)")
wrap_site(g)

dev.off()

# * figs--monthly means ------------------------------------------------
pdf("figures/original_vs_markov_monthly_v1.pdf")

p <- ggplot(monthly_ppt, aes(x = month, color = manip, linetype = markov)) +
  facet_wrap(~site) +
  scale_color_manual(values = cols2) +
  scale_x_continuous(breaks = 1:12) 

# ppt
p +
  geom_line(aes(y = PPT_m)) +
  labs(y = "PPT (cm)",
       subtitle = "Mean monthly precipitation")

p +
  geom_line(aes(y = PPT_med)) +
  labs(y = "PPT (cm)",
       subtitle = "Median monthly precipitation")
# max temp
p +
  geom_line(aes(y = Tmax_m)) +
  labs(y = "Temperature (C)",
       subtitle = "Mean monthly daily max temp")

p +
  geom_line(aes(y = Tmin_m)) +
  labs(y = "Temperature (C)",
       subtitle = "Mean monthly daily min temp")

dev.off()


# * figs mean annual diff  ------------------------------------------------

cap1 <- "weather simulated using stepwat2 for 300 yrs, coeffs adjusted to \ndouble ppt intensity"
diff_figs <- function(data, 
                      orig_amb,
                      orig_2x) {
  
  ggplot(data, aes(y = site)) +
    geom_vline(xintercept = 0, linetype = 2) +
    geom_point(aes(x = .data[[orig_amb]], color = "sim ambient - original")) +
    geom_point(aes(x = .data[[orig_2x]], color = "sim 2x - original")) +
    scale_color_manual(values = c("sim ambient - original" = "blue",
                                  "sim 2x - original" = "red")) +
    theme(legend.position = "top") +
    labs(caption = cap1)
    #geom_point(aes(x = .data[[amb_2x]], color = "sim 2x - sim ambient")) 
}


pdf("figures/original_vs_markov_mean_annual_v1.pdf")
diff_figs(data = diffs_mean_annual,
          orig_amb = "map_orig_amb_diff",
          orig_2x = "map_orig_2x_diff") +
  labs(subtitle = "Differences between MAP of simulated ambient and 2x intensity ppt, \n and observed (weather db) MAP ",
       x = "Mean annual ppt difference (mm)")

# Note: there is a problem with here--tmax adjustment not working!
diff_figs(data = diffs_mean_annual,
          orig_amb = "Tmax_orig_amb_diff",
          orig_2x = "Tmax_orig_2x_diff") +
  labs(subtitle = "Differences between mean of simulated ambient and 2x intensity Tmax, \n and observed (weather db) Tmax ",
       x = "Temperature difference (C)")

diff_figs(data = diffs_mean_annual,
          orig_amb = "Tmin_orig_amb_diff",
          orig_2x = "Tmin_orig_2x_diff") +
  labs(subtitle = "Differences between mean of simulated ambient and 2x intensity Tmin, \n and observed (weather db) Tmin ",
       x = "Temperature difference (C)")
dev.off()
# *figs distribution by doy -----------------------------------------------

dly_amb_gt0 %>% 
  # don't want to plot all DOYs
  filter(DOY %in% seq(from = 20, to = 360, by = 40), !is_prev_wet) %>% 
  ggplot(aes(PPT, linetype = markov))+
  geom_density() +
  facet_grid(DOY~site, scales = 'free')
