# Martin Holdrege

# Script Started 12/9/20

# First stab at manipulating precipitation intensity from the wx database.

# NEXT: see why MAP of some sites is on with 2x intensity
# Also adjust colors (naming cols2 vector caused problems, 
# maybe name vector further down instead)
# figures/original_vs_markov_distributions_v2.pdf needs to be updated
# to make figures of adjusted coeff simulated values instead

# dependencies ------------------------------------------------------------

library(tidyverse)
library(lubridate)
library(DBI)
library(precipr) # devtools::install_github("MartinHoldrege/precipr")
library(rSOILWAT2)

source("scripts/functions.R")
theme_set(theme_classic())

# connect to database -----------------------------------------------------

db_path <- "../dbWeather/dbWeatherData_STEPWAT2_200sites.sqlite3"

rSOILWAT2::dbW_setConnection(db_path, check_version = TRUE)

# load markov ppt ---------------------------------------------------------

# ppt generated by stepwat2 and adjusted coeff files in the 01_
# simulate-wx_14site.R script

ppt_path <- "../sitedata/ppt/markov_ppt_14sites_20210407.csv"
ppt_markov0<- read_csv(ppt_path)

ppt_markov <- ppt_markov0 %>% 
  rename(PPT = PPT_cm, year = Year, manip = intensity) %>% 
  mutate(markov = TRUE) # sim by markov process.

# extract current scenarios -----------------------------------------------

# Diverse set of representative sites from KP
sites <- c(5, 15, 74, 76, 102, 103, 119, 124, 141, 156, 162, 172, 177, 184)
names(sites) <- as.character(sites)
sw_weatherList<- map(sites, dbW_getWeatherData, Scenario = "Current")

# extract all precip yrs/sites --------------------------------------------

# combine into single df
comb_wx <- map_dfr(sw_weatherList, function(x) {
  wdata_df <- dbW_weatherData_to_dataframe(x) %>% 
    as.data.frame()
}, .id = "site") %>% 
  mutate(site = as.numeric(site)) %>% 
  rename(year = Year)

# saving file of just site 5 for code testing
comb_wx %>% 
  filter(site == 5) %>% 
  mutate(first = paste0(year, "-01-01"),
         date = as.Date((DOY-1), origin = first),
         month = month(date),
         day = mday(date)) %>% 
  select(site, year, month, day, date, everything(), -first) %>% 
  write_csv("data-raw/wx_ambient_site-5.csv")

# manipulate precip -------------------------------------------------------

comb_wx2 <- comb_wx %>% 
  arrange(site, year, DOY) %>% 
  # for now grouping by year to insure annual precip unchanged
  group_by(site, year) %>% 
  mutate(dly_2x_intensity = incr_dly_intensity(PPT_cm), # double daily intensity
         event_2x_intensity = incr_event_intensity(PPT_cm)) # double event

manip_lookup <- c("PPT_cm" = "ambient", "dly_2x_intensity" = "dly 2x intensity",
                  "event_2x_intensity" = "event 2x intensity")

comb_wx_long <- comb_wx2 %>% 
  pivot_longer(matches("PPT_cm|_intensity"), names_to = "manip", 
               values_to = "PPT") %>% 
  mutate(manip = manip_lookup[manip])

# yearly summaries

yrly_df_all <- comb_wx_long %>% 
  mutate(markov = FALSE) %>% 
  bind_rows(ppt_markov) %>% 
  # yearly summaries
  group_by(site, year, manip, markov) %>% 
  summarise(# number of days with precip
            n_days = sum(PPT > 0),
            # annual precip
            ap = sum(PPT),
            # mean precip on days w/ precip
            mean_PPT = ap/n_days,
            med_PPT = median(PPT[PPT > 0]),
            n_events = n_events(PPT, min_length = 1),
            n_multi_events = n_events(PPT, min_length = 2),
            max_event_length = max_event_length(PPT),
            prop_multi_events = n_multi_events/n_events,
            mean_event_size = mean_event_size(PPT),
            n_small = sum(PPT > 0 & PPT < 0.1),
            mean_Tmax = mean(Tmax_C),
            mean_Tmin = mean(Tmin_C)) # number of small events



# note this year has 0 ppt. Is that just chance or an issue with 
# the coeff adjustment?
yrly_df_all %>% 
  filter(ap == 0)

# compare original and markov ---------------------------------------------

comb_wx_long2 <- comb_wx_long %>% 
  # now just looking at original ambient
  # filter(manip %in% c("ambient", "event 2x intensity"))
  filter(manip %in% c("ambient")) %>% 
  mutate(markov = FALSE) %>%  # not simulated by stepwat--ie from wx db
  bind_rows(ppt_markov)

yrly_df_all2 <- yrly_df_all %>% 
  # here 2x intensity was applied via adjusting markov coeffs
  filter(manip %in% c("ambient", "2x intensity"))

# monthly precip ----------------------------------------------------------

# monthly mean ppt across years within a site. 
monthly_ppt <- comb_wx_long2 %>% 
  mutate(date = as.Date(DOY-1, origin = paste0(year, "-01-01")),
         month = lubridate::month(date)) %>% 
  group_by(year, month, site, manip, markov) %>% 
  summarize(PPT = sum(PPT),
            Tmax_C = mean(Tmax_C),
            Tmin_C = mean(Tmin_C), 
            .groups = "drop") %>% 
  group_by(month, site, manip, markov) %>% 
  summarize(PPT_sd = sd(PPT),
            PPT_m = mean(PPT),
            PPT_med = median(PPT),
            Tmax_sd = sd(Tmax_C),
            Tmax_m = mean(Tmax_C),
            Tmax_med = median(Tmax_C),
            Tmin_sd = sd(Tmin_C),
            Tmin_m = mean(Tmin_C),
            Tmin_med = median(Tmin_C),
            .groups = "drop")
  

# mean_annual_diffs -------------------------------------------------------
# mean diffs of temp and precip
        
mean_annual <- yrly_df_all %>% 
  filter(!str_detect(manip, "dly|event")) %>% 
  group_by(site, manip, markov) %>% 
  summarize(map = mean(ap),
            ap_sd = sd(ap),
            Tmax = mean(mean_Tmax),
            Tmin = mean(mean_Tmin),
            n_days = mean(n_days),
            .groups = "drop")


diffs_mean_annual <- mean_annual%>% 
  mutate(manip = str_replace(manip, " ", "_"),
         manip_markov = paste(manip, markov, sep = "_")) %>% 
  select(-manip, -markov) %>% 
  pivot_wider(id_cols = c("site"),
              values_from = c("map", "Tmax", "Tmin"),
              names_from = "manip_markov") %>% 
  mutate(site = as.character(site),
         site = factor(site, levels = sites),
         # difference between original and simulated ambient map
         map_orig_amb_diff =  map_ambient_TRUE - map_ambient_FALSE,
         # original vs simulated 2x map
         map_orig_2x_diff = map_2x_intensity_TRUE - map_ambient_FALSE,
         # simulated ambient vs 2x map
         map_amb_2x_diff = map_2x_intensity_TRUE - map_ambient_TRUE,
         Tmax_orig_amb_diff =  Tmax_ambient_TRUE - Tmax_ambient_FALSE,
         Tmax_orig_2x_diff = Tmax_2x_intensity_TRUE - Tmax_ambient_FALSE,
         Tmax_amb_2x_diff = Tmax_2x_intensity_TRUE - Tmax_ambient_TRUE,
         Tmin_orig_amb_diff =  Tmin_ambient_TRUE - Tmin_ambient_FALSE,
         Tmin_orig_2x_diff = Tmin_2x_intensity_TRUE - Tmin_ambient_FALSE,
         Tmin_amb_2x_diff = Tmin_2x_intensity_TRUE - Tmin_ambient_TRUE
         ) 

# figure functions --------------------------------------------------------

if (!dir.exists("figures")) {
  dir.create("figures")
}

density_rug <- function(x) {
  list(geom_density(aes(.data[[x]])),
       geom_rug(aes(.data[[x]]), sides = "b"))
}

cols1 <- c("blue", "black", "red") 
cols2 <- c("blue", "red")
names(cols2) <- c("ambient", "2x intensity")
# distributional figures --------------------------------------------------

# these figures are no longer really of much interest--so have removed code
# on 4/11/21 (they were based on adding/removing events type manipulation)


# figs--markov vs original ------------------------------------------------

pdf("figures/original_vs_markov_distributions_v2.pdf")

# * figs -- daily distributions -------------------------------------------

ggplot(comb_wx_long2[comb_wx_long2$PPT > 0, ], 
            aes(x = PPT, color = manip, linetype = markov)) +
  geom_density() +
  labs(x = "Daily PPT (cm)",
       title = "Daily event size (days > 0 ppt), original vs markov simulated") +
  scale_color_manual(values =cols2) +
  facet_wrap(~site, scales = "free")

# * figs -- yrly distributions -------------------------------------------

g2 <- ggplot(yrly_df_all2, aes(color = manip, linetype = markov)) +
  scale_color_manual(values = cols2) +
  labs(subtitle = "by site",
       caption = "Distributions of yearly summaries, markov vs original\n Intensity manipulated by adjusting markov coeffs.")


g <- g2 +
  geom_density(aes(med_PPT)) +
  labs(title = "Median daily PPT on days with PPT")

wrap_site(g)

g <- g2 +
  geom_density(aes(mean_PPT)) +
  labs(title = "Mean daily PPT on days with PPT") 

wrap_site(g)

g <- g2 +
  geom_density(aes(ap)) +
  labs(title = "Annual precip",
       x = "Annual PPT (cm)")

wrap_site(g)

g <- g2 +
  geom_density(aes(n_days)) +
  labs(title = "number of days per year with precip")

wrap_site(g) 

g <- g2 +
  geom_density(aes(n_events)) +
  labs(title = "Number of precipitation events (periods with 1 or more consecutive rain days)",
       x = "N events")

wrap_site(g) 

g <- g2 +
  geom_density(aes(n_multi_events)) +
  labs(title = "Number of multiday (>=2 days) precip events",
       x = "N events)")
wrap_site(g)
g<- g2 +
  geom_density(aes(max_event_length)) +
  labs(title = "Maximum event length (number of consecutive days)",
       x = "Days")
wrap_site(g)

g <- g2 +
  geom_density(aes(prop_multi_events))+
  labs(title = "Proportion of precip events that are multiday",
       x = "Proportion")
wrap_site(g)

g <- g2 +
  geom_density(aes(mean_event_size)) +
  labs(title = "Mean event size (event = consecutive ppt days)",
       x = "Mean event size (cm)")
wrap_site(g)

dev.off()

# * figs--monthly means ------------------------------------------------

pdf("figures/original_vs_markov_monthly_v2.pdf")

p <- ggplot(monthly_ppt, aes(x = month, color = manip, linetype = markov)) +
  facet_wrap(~site) +
  scale_color_manual(values = cols2) +
  scale_x_continuous(breaks = 1:12) 

# ppt
p +
  geom_line(aes(y = PPT_m)) +
  labs(y = "PPT (cm)",
       subtitle = "Mean monthly precipitation")

p +
  geom_line(aes(y = PPT_med)) +
  labs(y = "PPT (cm)",
       subtitle = "Median monthly precipitation")

p +
  geom_line(aes(y = PPT_sd)) +
  labs(y = "PPT SD (cm)",
       subtitle = "Standard deviation (between years) of monthly precipitation")

p +
  geom_line(aes(y = PPT_sd/PPT_m)) +
  labs(y = "Coefficient of variation (sd/mean)",
       subtitle = "Coefficient of variation of monthly precipitation (between year variability)")

# max temp
p +
  geom_line(aes(y = Tmax_m)) +
  labs(y = "Temperature (C)",
       subtitle = "Mean monthly daily max temp")

p +
  geom_line(aes(y = Tmin_m)) +
  labs(y = "Temperature (C)",
       subtitle = "Mean monthly daily min temp")

dev.off()


# * figs mean annual diff  ------------------------------------------------

cap1 <- "weather simulated using stepwat2 for 300 yrs, coeffs adjusted to \ndouble ppt intensity"
diff_figs <- function(data, 
                      orig_amb,
                      orig_2x) {
  
  ggplot(data, aes(y = site)) +
    geom_vline(xintercept = 0, linetype = 2) +
    geom_point(aes(x = .data[[orig_amb]], color = "sim ambient - original")) +
    geom_point(aes(x = .data[[orig_2x]], color = "sim 2x - original")) +
    scale_color_manual(values = c("sim ambient - original" = "blue",
                                  "sim 2x - original" = "red")) +
    theme(legend.position = "top") +
    labs(caption = cap1)
    #geom_point(aes(x = .data[[amb_2x]], color = "sim 2x - sim ambient")) 
}


pdf("figures/original_vs_markov_mean_annual_v3.pdf")

diff_figs(data = diffs_mean_annual,
          orig_amb = "map_orig_amb_diff",
          orig_2x = "map_orig_2x_diff") +
  labs(subtitle = "Differences between MAP of simulated ambient and 2x intensity ppt, \n and observed (weather db) MAP ",
       x = "Mean annual ppt difference (cm)")

# Note: there is a problem with here--tmax adjustment not working perfectly
diff_figs(data = diffs_mean_annual,
          orig_amb = "Tmax_orig_amb_diff",
          orig_2x = "Tmax_orig_2x_diff") +
  labs(subtitle = "Differences between mean of simulated ambient and 2x intensity Tmax, \n and observed (weather db) Tmax ",
       x = "Temperature difference (C)")

diff_figs(data = diffs_mean_annual,
          orig_amb = "Tmin_orig_amb_diff",
          orig_2x = "Tmin_orig_2x_diff") +
  labs(subtitle = "Differences between mean of simulated ambient and 2x intensity Tmin, \n and observed (weather db) Tmin ",
       x = "Temperature difference (C)")

# nwet ratio
mean_annual %>% 
  filter(markov) %>% 
  group_by(site) %>% 
  summarize(nwet_ratio = n_days[manip == "2x intensity"]/n_days[manip == "ambient"],
            .groups = "drop") %>% 
  ggplot(aes(nwet_ratio, as.factor(site))) + 
  geom_vline(xintercept = 0.5, linetype = 2) +
  geom_point() +
  labs(caption = cap1,
       y = "site",
       x = "(n wet days 2x intensity)/(n wet days ambient)",
       subtitle = "Ratio of number of wet days in 2x intensity versus ambient simulations")
  
# interannual ppt ratio
mean_annual %>% 
  group_by(site) %>% 
  summarize(ap_ratio = ap_sd[manip == "2x intensity"]/ap_sd[manip == "ambient"]) %>% 
  ggplot(aes(ap_ratio)) +
  geom_histogram(bins = 10) +
  labs(caption = cap1,
       x = "(interannual ppt sd 2x)/(interannual ppt sd ambient)",
       subtitle = "Ratio of interannual PPT standard dev, 2x intensity:ambient") +
  geom_vline(xintercept = 1, linetype = 2)

# CV
mean_annual %>% 
  mutate(CV = ap_sd/map) %>% 
  ggplot(aes(x = CV, y = as.factor(site), color = manip, shape = markov)) + 
  geom_hline(aes(yintercept = as.factor(site)), linetype = 3, color = "grey",
             alpha = 0.5) +
  geom_point() +
  scale_color_manual(values = cols2) +
  labs(y = "site",
       x = "CV (sd/mean)",
       caption = cap1,
       title = "Coefficient of variation of annual precipitation")

dev.off()

